### ISSUE TITLE
replace travis ci with github actions

### ISSUE THREAD

**Issue by EricCrosson** [EricCrosson/generator-typescript-package#128]
https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

sucks to your assmar

**Comment by EricCrosson** [comment]
is this a thing? was in the blog post i read. not sure if this is a thing https://github.com/rosineygp/mkdkr

**Comment by EricCrosson** [comment]
Or drone, the public offering was a breeze to set up in github.com/ericcrosson/dotfiles

**Comment by ericcrosson-bitgo** [comment]
nope, drone hit the same fate as travis ci: acquisition -> defunding public plans

github actions still free 
![image](https://user-images.githubusercontent.com/67922293/137549157-18737eb2-fd93-4bae-9885-b6b6a8448ba6.png)
