### ISSUE TITLE
Add tests to avoid breaking master

### ISSUE THREAD

**Issue by amchelle** [EricCrosson/generator-typescript-package#13]
Modifications branch is working though

**Comment by EricCrosson** [comment]
upon successful ci, push a demo project to a `demo` branch

**Comment by amchelle** [comment]
Master is not broke anymore, but you should probably add those tests

**Comment by amchelle** [comment]
jk still broke. finding a patch

**Comment by amchelle** [comment]
Fixed with v1.0.23 :sunglasses:

**Comment by EricCrosson** [comment]
Thanks for your service :+1:

**Comment by EricCrosson** [comment]
https://yeoman.io/authoring/testing.html

Brings up a good question - should the lerna customizations be a sub-generator?

**Comment by EricCrosson** [comment]
- [X] unit tests
- [ ] yeoman tests

**Comment by EricCrosson** [comment]
Replacing this issue for bookkeeping with #88
