### ISSUE TITLE
Supply smarter default for 'your hosted git repository (https'

### ISSUE THREAD

**Issue by EricCrosson** [EricCrosson/generator-typescript-package#16]
In order, check

- local git remote (origin)

**Comment by amchelle** [comment]
and then convert it from ssh to https

**Comment by EricCrosson** [comment]
https://github.com/sindresorhus/git-remote-origin-url

- need to determine how to run async tasks in yeoman generators
- need a package to convert ssh urls to https

**Comment by EricCrosson** [comment]
Does this only apply to lerna projects? No, one can start a non-lerna project by cloning an empty repo
